### PR TITLE
Fix bug in frontend_start

### PR DESCRIPTION
**Pull request by andrewjennings**
Update script to run the file that it checked.

### CODE REVIEW

**Comment by andrewjennings** [comment]
Fix for #125 .

**Comment by dscx** [comment]
I am very curious to see if this works for others. Is this an edit that effects something in compile/build perhaps? Or a hidden file, since it is a script? Simply changing these lines once the file is generated, direct on device, does not fix the issue, for me or many others.

**Comment by andrewjennings** [comment]
This script is part of the init process. The script looks for a simplemenu opk (both the 350 and 350m version) on each SD Card. It's supposed to run the OPK that it finds, but instead it's checking for one file, then trying to run a different one.

Every time you use the GUI to "install" simplemenu as the default, this script is overwritten. Maybe that's your problem. Or maybe it's the permissions on the file if you're manually downloading, editing, and uploading.  I think it has to be executable.

Here's what worked for me, presuming you already have simplemenu installed and configured.
- Enter simplemenu menu with start and select "Default Launcher" -> Yes
- SSH to your RG350m
- Use vi to edit /media/data/local/sbin/frontend_start with the fix
- Type "reboot" in your terminal to reboot

Hope that helps.

**Comment by dscx** [comment]
Ah a permission issue makes sense here. Will report back

**Comment by dscx** [comment]
@andrewjennings does this look correct in vi? File has 777 permission

Screen Shot 2020-08-30 at 10 56 20 AM

**Comment by dscx** [comment]
Last update - it worked!

Turns out when you copy the file first, it adds those ^M but they're hidden in other editors, such as VSCode. Editing in place via SSH as you suggested is the secret here.

@andrewjennings  THANK YOU!

**Comment by andrewjennings** [comment]
Glad it helped!  Credit really goes to the folks who figured it out in the two issues I marked. I'm just putting their findings in a way that's easy for @fgl82 to pull in as a fix.

BTW, those ^M characters are "carriage returns". They're Windows/DOS-style line endings.

**Pull request merged**
